name: Build and push container image 

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        # https://github.com/docker/metadata-action
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            yteraoka/test-http-server
            ghcr.io/yteraoka/test-http-server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        # https://github.com/docker/login-action
        uses: docker/login-action@v2
        with:
          username: yteraoka
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        # https://github.com/docker/login-action
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
